### PR TITLE
Update dh-boost-container.py

### PR DESCRIPTION
**Pull request by Youw**
Make it work with Qt Creator 4.
Tested with Qt Creator 4.15.2.

### CODE REVIEW

**Comment by awulkiew** [comment]
Thanks! This probably doesn't work with QtCreator3 right? If that's the case shouldn't this be a separate file?

**Comment by Youw** [comment]
It probably doesn't.
But does anyone still using Qt Creator 3?
Maybe just make a branch/tag, and keep support of QtCreator4 only in master.

Also, I think I'll try to add it to the Qt Creator itself:
https://github.com/qt-creator/qt-creator/pull/44

**Comment by awulkiew** [comment]
Right, thought I'd prefer to keep it in the same branch. A separate directory in the repo would be fine. Note that there are many other helpers here. They probably will not work with QtCreator4.

**Comment by awulkiew** [comment]
Btw, feel free to add your copyrights.

**Comment by Youw** [comment]
> Note that there are many other helpers here.

Yeah, I've only updated what I've personally used&tested.

**Comment by awulkiew** [comment]
My point was that if helpers for ver3 were moved to a different branch they would be "hidden" if ver4 branch was the official/main one. But more importantly after this change there would be only one helper in ver4 branch. I don't think that we should hide helpers based on the number of users of specific versions, assuming this number is publicly available. Furthermore there is ver5 now.

So please create a new file with the helpers or if you don't have time let me know so I'll do it.

**Comment by Youw** [comment]
I will, in a bit.

**Pull request closed without merging**
